Tried a better start stop implementation, like Volvo or BMW or KIA...

diff --git a/templates/logstash_indexer.j2 b/templates/logstash_indexer.j2
--- a/templates/logstash_indexer.j2
+++ b/templates/logstash_indexer.j2
@@ -53,7 +53,7 @@ do_start()
 	# start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- \
 	# 	$DAEMON_ARGS \
 	# 	|| return 2
-	pgrep -f "^.*${DAEMON}$" > /dev/null
+	pgrep -f "^.*${DAEMON} ${DAEMON_ARGS}$" > /dev/null
     if [ "$?" =  1 ]; then
     	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- \
 	 	$DAEMON_ARGS
@@ -73,9 +73,9 @@ do_stop()
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
+	#start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	#RETVAL="$?"
+	#[ "$RETVAL" = 2 ] && return 2
 	# Wait for children to finish too if this is a daemon that forks
 	# and if the daemon is only ever run from this initscript.
 	# If the above conditions are not satisfied then add some other code
